### PR TITLE
rewrite: command structure clean-up

### PR DESCRIPTION
**Pull request by LawMixer**

### CODE REVIEW

**Comment by Hedwig7s** [comment]
Why is stdio.write being used over print? The only difference (at least in this situation) is stdio.write doesn't append a \n

**Comment by LawMixer** [comment]
Print doesn't have rich text (example for the colors) - I'm just copying what was previously there;

**Comment by Hedwig7s** [comment]
The original file had print and colors worked fine
I do not see the purpose of using stdio.write

**Comment by LawMixer** [comment]
> The original file had print and colors worked fine I do not see the purpose of using stdio.write

It writes directly to stdio/stdout without the auto formatting print/warn/error has which was causing further issues with me using the logging functions;

**Comment by AsynchronousAI** [comment]
If you want to clean it use a for loop and table to hold the command name, descriptions, and color.

**Comment by LawMixer** [comment]
I'll probably play around with somethings, just wanted to do release this so that we can keep moving on the development;

**Comment by AsynchronousAI** [comment]
> I'll probably play around with somethings, just wanted to do release this so that we can keep moving on the development; 

No problem

**Pull request merged**
